version: 2
workflows:
    version: 2
    test_deploy:
        jobs:
            - python-2
            - python-3

jobs:
    python-3:
        docker:
            - image: circleci/python:3.6.2-stretch-browsers
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "test-requirements.txt" }}

            - run:
                name: install dependencies
                command: |
                    rm -rf venv
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r test-requirements.txt

            - save_cache:
                paths:
                    - ./venv
                key: v1-dependencies-{{ checksum "test-requirements.txt" }}

            - run:
                name: run tests
                command: |
                    . venv/bin/activate
                    py.test

            - run:
                name: lint code (use uppercase TODO, XXX, FIXME, NOTE and explain nopep8)
                command: |
                  make lint-comment

            - run:
                name: lint code (pycodestyle)
                command: |
                  . venv/bin/activate
                  make lint-pycodestyle

            - run:
                name: lint code (pylint)
                command: |
                  . venv/bin/activate
                  make lint-pylint

            - store_artifacts:
                path: test-reports
                destination: test-reports

    python-2:
        docker:
            - image: circleci/python:2.7
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "test-requirements.txt" }}

            - run:
                name: install dependencies
                command: |
                    rm -rf venv
                    python -m venv venv || virtualenv venv
                    . venv/bin/activate
                    pip install --upgrade -r test-requirements.txt | cat

            - save_cache:
                paths:
                    - ./venv
                key: v1-dependencies-{{ checksum "test-requirements.txt" }}

            - run:
                name: run tests
                command: |
                    . venv/bin/activate
                    py.test

            - run:
                name: lint code (use uppercase TODO, XXX, FIXME, NOTE and explain nopep8)
                command: |
                  make lint-comment

            - run:
                name: lint code (pycodestyle)
                command: |
                  . venv/bin/activate
                  make lint-pycodestyle

            - run:
                name: lint code (pylint)
                command: |
                  . venv/bin/activate
                  make lint-pylint

            - store_artifacts:
                path: test-reports
                destination: test-reports
