# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
workflows:
    version: 2
    test_deploy:
        jobs:
            - test-3.6
            - test-2.7
            - deploy:
                requires:
                    - test-3.6
                    - test-2.7
                filters:
                    tags:
                        only: /[\d.]+/
                    branches:
                        ignore: /.*/

jobs:
    test-3.6: &test-template
        docker:
            - image: circleci/python:3.6.1
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "test-requirements.txt" }}
                    - v1-dependencies-

            - run:
                name: install dependencies
                command: |
                    python -m venv venv || virtualenv venv
                    . venv/bin/activate
                    pip install -r test-requirements.txt

            - save_cache:
                paths:
                    - ./venv
                key: v1-dependencies-{{ checksum "test-requirements.txt" }}

            - run:
                name: run tests
                command: |
                    . venv/bin/activate
                    py.test

            - store_artifacts:
                path: test-reports
                destination: test-reports
    test-2.7:
        <<: *test-template
        docker:
          - image: circleci/python:2.7

    deploy:
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "test-requirements.txt" }}
                    - v1-dependencies-

            - run:
                name: install dependencies
                command: |
                    python -m venv venv || virtualenv venv
                    . venv/bin/activate
                    pip install -r test-requirements.txt

            - save_cache:
                paths:
                    - ./venv
                key: v1-dependencies-{{ checksum "test-requirements.txt" }}
            - run:
                name: init .pypirc
                command: |
                    echo -e "[pypi]" >> ~/.pypirc
                    echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
                    echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

            - run:
                name: create packages
                command: |
                    make package

            - run:
                name: upload to pypi
                command: |
                    . venv/bin/activate
                    twine upload dist/*
